# Generated by Django 5.0.2 on 2024-02-25 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contracts", "0002_initial"),
        ("events", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.client"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contracts.contract"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="support_contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_support_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
