# Generated by Django 5.0.2 on 2024-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.FloatField()),
                ("remaining_amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Sign", "Sign"), ("To-sign", "To Sign")],
                        max_length=10,
                    ),
                ),
                ("creation_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
